@startuml elfa-job-diario
title Job Apuração de Delta (diário)

control     Alteryx as job
database    DB_Protheus as db
collections Mongodb as mongo
control     API_Impostos as api_imposto
control     Protheus as protheus
control     API_Calculadora as api_calculadora
control     API_Persistencia as api_persistencia

group Consulta tabelas base
job -> db: Consultar tabelas (D0)
db -> job: Retornar tabelas base 
end 

group Apuração de Delta
job -> mongo: Consultar collections (D-1)
mongo -> job: Retornar collections base
job -> job: Apurar o Delta (Protheus - Mongo)
end

job ->  api_imposto: Enviar Delta
api_imposto -> protheus: Enviar dados Delta
protheus -> api_imposto: Retornar os calculos de impostos
api_imposto -> job: Retornar os calculos de impostos
job -> api_calculadora: Enviar base final a ser \najustada pela calculadora

group Camada de Persistencia
api_calculadora -> api_persistencia: Enviar dados completos para persistencia
api_persistencia -> mongo: Persistentir dados
end
@enduml
