@startuml skill-management-1.0
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
title Skill Management - 1.0

LAYOUT_LANDSCAPE()

Person(user, "Adm")
Person(final_user, "Usuários finais")


System_Boundary(external_systems, "External Systems") {
    ContainerDb(excel_base, "Planilhas (Base)", "Excel", "Repositório de dados")
}

System_Boundary(datalake, "Data Lake") {
    ContainerDb(excel, "Repositório de Processos", "Excel", "Repositório de dados")

}

System_Boundary(system, "System") {

    System_Boundary(data_ops, "Data Pipeline") {
        Container(orchestration, "Orchestration", "python", "")
        Container(el, "Data Ingestion", "python", "")
        Container(transformation, "Data Transformation", "dbt", "")
    }

    System_Boundary(software, "Software") {
        ContainerDb(database, "database", "MySQL", "Repositório de dados")
        Container(api, "API", "Python", "Backend")
        Container(ui, "UI", "Angular", "Frontend")   
        Container(notifify, "Notifify", "", "")
    }   
}


Rel(orchestration, el, "Schedule job")
Rel(orchestration, transformation, "Schedule job")

Rel(user, excel_base, "Exportar para versão de integração")
Rel(user, excel, "Criar e copiar para data lake")
Rel(excel, el, "Carregar dados")
Rel(el, database, "Salvar dados")
BiRel(transformation, database, "Carregar, transformar e salvar nome")

Rel(api, database, "Carregar, transformar e salvar nome")
Rel(ui, api, "User Interface")

Rel(database, notifify , "Ler informações" )
Rel(notifify, final_user, "Notificar conforme os eventos")


@enduml
