@startmindmap skill-management-1.0

title Skill Management 1.0

* Captura de Projetos
** Who (person)
*** MD

** Where
*** Sales Force
*** PowerApps
*** Emails

** What 
*** Enviar emails com Excel

** Repos
*** Excel
*** Projects

** Integrations

@endmindmap
