@startuml diagrama-aws
' Uncomment the line below for "dark mode" styling
'!$AWS_DARK = true

title Elfa - Processo de cálculo de margem de venda - v1.3
footer fonte github.com

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v18.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/BusinessApplications/all.puml
!include AWSPuml/Storage/SimpleStorageService.puml
!include AWSPuml/AWSSimplified.puml
!include AWSPuml/Compute/EC2.puml
!include AWSPuml/Compute/EC2Instance.puml
!include AWSPuml/Groups/AWSCloud.puml
!include AWSPuml/Groups/VPC.puml
!include AWSPuml/Groups/AvailabilityZone.puml
!include AWSPuml/Groups/PublicSubnet.puml
!include AWSPuml/Groups/PrivateSubnet.puml
!include AWSPuml/NetworkingContentDelivery/VPCNATGateway.puml
!include AWSPuml/NetworkingContentDelivery/VPCInternetGateway.puml
!include AWSPuml/ApplicationIntegration/APIGateway.puml
!include AWSPuml/ApplicationIntegration/StepFunctions.puml
!include AWSPuml/Compute/Lambda.puml
!include AWSPuml/Analytics/Glue.puml
!include AWSPuml/Analytics/Athena.puml
!include AWSPuml/Database/Aurora.puml
!include AWSPuml/FrontEndWebMobile/Amplify.puml


AWSCloudGroup(aws, "AWS") {

    AWSCloudGroup(data, "Data Services") {
        APIGateway(apiGateway, "APIGateway", "APIGateway")
        Lambda(lambdaData, "Lambda", "")
        SimpleStorageService(raw, "Raw", "Raw", "Raw")
        Glue(glue, "Glue", "Glue")
        SimpleStorageService(cleaned, "Cleaned", "Cleaned", "Cleaned")
        Athena(athena, "Athena", "Athena")

        apiGateway --> lambdaData
        lambdaData --> raw: Persistir
        raw --> glue: On Create
        glue --> cleaned
        athena -u-> cleaned
    }

    AWSCloudGroup(core, "Core Services") {
        Lambda(lambdaCore, "Lambda", "")
        StepFunctions(stepFunctions, "StepFunctions", "")
        Aurora(aurora, "Aurora", "")
        cloud external_Api 

        stepFunctions --> lambdaCore: Orchestrates
        lambdaCore --> aurora
        lambdaCore --> external_Api: Integrates with
    }

    AWSCloudGroup(app, "App Services") {
        Amplify(amplify, "Amplify", "")
    }

    lambdaCore --> athena
    aurora <-- amplify
}






@enduml