@startuml skill-management-entity-1.0

skinparam linetype ortho


entity "Usuários" as usuario {
  *id : number 
  --
  *name : text
  type: enum [MD, ADM, FINAL, PROFI]
}

entity "Setores" as setor {
  *id : number 
  --
  *name : text
}

entity "Clientes" as cliente {
  *id : number 
  --
  *name : text
}

entity "Produtos" as produto {
  *id : number 
  --
  *name : text 
}

entity "Projetos" as projeto {
  *id : number 
  --
  *name : text
}

entity "Ferramentas" as tool {
  *id : number 
  --
  *name : text
  link: text
  softwares: list
  gerente: number
  produto: number
}

entity "Softwares" as software {
  *id : number 
  --
  *name : text
}


entity "Documentos" as documento {
  *id : number 
  --
  *name : text
  type: enum[Proposta/PoV/Tese/Contrato]
  sharepoint_url: text
  created_at: timestamp
  update_at: timestamp
}

usuario ||--o{ tool
tool ||--o{ software

@enduml
