@startmindmap skill-management-1.0

title Skill Management 1.0

* Captura de Projetos
** Who (person)
*** MD, Usuário Final, ADM, Profissionais

** Where
*** Sales Force
*** PowerApps
*** Emails

** What (Features)
*** Enviar emails com Excel
*** Controlar mapeado, porém não recebido
*** Qualificar os relacionamentos do Linkedin


** Repos
*** Excel
*** Projects
*** Super Pesquisa
**** Elastic Search
**** Nível de Permissionamento

** Integrations

@endmindmap
